<?php
/**
 * @Author: Mathieu VIALES
 * @Date:   2016-10-19 17:02:06
 * @Last Modified by:   Mathieu VIALES
 * @Last Modified time: 2016-10-19 18:04:58
 */

namespace Entity\User;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * List of errors - an error is a plain string error message
	 */
	private $_errors = [];

	/**
	 * Make sure the User's properties that must be unique actually are unique
	 */
	public function isPersistable(User $user)
	{
		// Ensure that the Username is unique
		$oneByUsername = $this->findOneBy(array('username' => $user->getUsername()));
		if($oneByUsername != null)
			array_push($this->_errors, 'Nom de famille déjà utilisé');

		// Ensure the the email is unique
		$oneByEmail = $this->findOneBy(array('email' => $user->getEmail()));
		if($oneByEmail != null)
			array_push($this->_errors, 'Email déjà utilisé');

		return count($this->_errors) == 0;
	}

	/**
	 * Return the error list
	 */
	public function getErrors()
	{
		return $this->_errors;
	}
}
